# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Publish # 定义工作流的名称，在GitHub Actions界面中显示

on: # 定义触发工作流的事件
  push: # 当推送到仓库时触发
    tags: # 仅在推送标签时触发
      - 'v*' # 仅匹配以'v'开头的标签，如v1.0.0

jobs: # 定义工作流中要执行的任务
  npm-publish: # 定义一个名为npm-publish的任务
    name: npm publish # 设置任务的显示名称
    runs-on: macos-latest # 指定运行任务的虚拟环境为最新版Ubuntu

    steps: # 定义任务中的步骤序列
      - name: Setup Node.js # 第二步：设置Node.js环境
        uses: actions/setup-node@v4 # 使用官方的setup-node action的v4版本
        with: # 配置参数
          node-version: '18' # 指定Node.js版本为18
          registry-url: 'https://registry.npmjs.org/' # 设置npm注册表URL

      - name: Setup pnpm # 第三步：设置pnpm包管理器
        uses: pnpm/action-setup@v4 # 使用pnpm官方的action-setup的v2版本
        with: # 配置参数
          version: 9 # 指定pnpm版本为8

      - name: Install dependencies # 第四步：安装项目依赖
        run: pnpm install # 运行pnpm install命令安装依赖

      - name: Build package # 第五步：构建项目
        run: pnpm build # 运行pnpm build命令构建项目

      - name: Publish to NPM # 第六步：发布到NPM
        run: pnpm publish --no-git-checks # 运行发布命令，跳过git检查
        env: # 设置环境变量
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # 使用GitHub仓库中存储的NPM_TOKEN密钥进行认证
